### ISSUE TITLE
Gem not working with sorbet/pronto?

### ISSUE THREAD

**Issue by hdoan741** [teamsimplepay/pronto-sorbet#1]
I don't know what's missing in my set up but it's not running or showing sorbet error.
```
$ bundle exec srb tc
app/graphql/types/base_field.rb:5: Not enough arguments provided for method Kernel#test. Expected: 2..3, got: 0 https://srb.help/7004
     5 |    test
            ^^^^
    https://github.com/sorbet/sorbet/tree/07a1414a7f06702d62729cde43c7ab705862fadb/rbi/core/kernel.rbi#L2540: Kernel#test defined here
    2540 |  def test(cmd, file1, file2=T.unsafe(nil)); end
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Errors: 1

# -- no output when running pronto
$ bundle exec pronto run

# -- sorbet is in the list of runners
$ bundle exec pronto list
rubocop
sorbet
```

This is the version of my gems:

    sorbet (0.5.5737)
    pronto (0.10.0)

**Comment by hdoan741** [comment]
Should the default here be `bundle exec srb`

```
          !path.empty? && File.executable?(path) ? path : 'srb'
```
https://github.com/teamsimplepay/pronto-sorbet/blob/master/lib/pronto/sorbet.rb#L13

**Comment by ashkulz** [comment]
Can you tell me:
* what's the version of `pronto-sorbet` you have installed? 
* what is the output of `srb tc`?
* does doing `git config pronto.sorbet "bundle exec srb"` give you correct output?

**Comment by hdoan741** [comment]
I install it today so it should be the latest version of pronto-sorbet

In the ticket I included srb tc output. Basically I add a simple error
(test) to trigger an error. Srb tc detects it but pronto run doesn’t show
anything

**Comment by hdoan741** [comment]
I tried to configure with `git config pronto.sorbet ‘bundle exec srb’` but
it doesn’t seem to work either.

**Comment by ashkulz** [comment]
Did you commit the code? Otherwise, you may need to [run with different options](https://github.com/prontolabs/pronto#local-changes) if there are local changes in your repository.

Otherwise, I'd really appreciate if you can upload a sample project somewhere -- the core logic does parse your output correctly.

**Comment by hdoan741** [comment]
I found the problem! It's because our rails repo is not at the root of the repo_path. It's in a sub-folder. This logic doesn't work for us:

```
        Dir.chdir(repo_path) do
           ...
        end
```
https://github.com/teamsimplepay/pronto-sorbet/blob/master/lib/pronto/sorbet.rb#L18

**Comment by ashkulz** [comment]
Can you describe the structure in more detail? I think this is a common pattern in Pronto wrappers, would love to hear more about how it can be improved. PRs welcome, of course :grin:

**Comment by hdoan741** [comment]
We have a root folder and 2 sub folders inside for server/ and client/.
Rails code is in the server/ folder.
I’m not familiar with pronto to judge what’s the best course of action
here. Is there a way to specify a root folder for pronto and use that
instead of the repo_path?

**Comment by ashkulz** [comment]
So, it'd be best if you attached a zip matching your structure with dummy files, so I can test out a fix (_as it's not a case encountered till now_).

Also, I'm not sure if executing `srb tc` works at all in the root folder? (which is what is happening right now) or it's giving output but filtered out in the next step (restricting to `ruby_patches`).

**Comment by ashkulz** [comment]
@manhhung741: do you still face this problem?

**Comment by ashkulz** [comment]
Please reopen this issue with the above details if it's still a problem :+1:
